#!/bin/bash
# Word count for report.tex (follows \include / \input).
#
#   Full    = words in text + headers + captions across the whole document.
#   Cleaned = manual-compliant body word count (Chapter 1 through final
#             Conclusion chapter) per project_assessment.pdf.
#             Excludes: abstract, references/bibliography, appendices,
#             figure/table captions, and all front matter (title page, ToC,
#             list of tables/figures/abbreviations, declaration, copyright,
#             acknowledgements).

cd "$(dirname "$0")"

UPDATE=0
if [ "$1" = "-u" ]; then
    UPDATE=1
fi

# Full: include everything via -inc, default sum (text+headers+captions).
FULL=$(texcount -inc -sum -1 -q report.tex 2>/dev/null | tail -n1)

# Cleaned: only the chapter sources (Ch1..Ch4 + Ch4R), text + headers, no captions.
# - References: in .bib, never counted by texcount.
# - Appendices: appendix_sections/ not in the file list.
# - Front matter (abstract, acknowledgements, abbreviations, ToC, lists,
#   title/declaration/copyright pages): not in the file list / generated by class.
CLEAN=$(texcount -inc -sum=1,1,0 -q -1 \
    chapter_1/main.tex \
    chapter_2/main.tex \
    chapter_3/main.tex \
    chapter_4R/main.tex \
    chapter_4/main.tex 2>/dev/null \
    | awk '{s+=$1} END {print s}')

echo "Full Word Count: $FULL"
echo "Cleaned Word Count: $CLEAN"

if [ "$UPDATE" = "1" ]; then
    echo "$CLEAN" > word.count
fi
